### ISSUE TITLE
Compatible with 1.1?

### ISSUE THREAD

**Issue by R-Bower** [ats-mods/Stormwalker#7]
Is an update required for compatibility with the most recent release?

**Comment by PoloBello** [comment]
With the 1.1.4 version of the game, the saves won't load with the Stormwalker tweak pack.
If the tweak pack completely, it's loading again, so I guess we'd need an update to use these wonderful mod again !

**Comment by R-Bower** [comment]
In-progress settlements won't load, but if you complete a run it will still save your progress.  Just means you need to finish what you start in a single session until we get an update!

**Comment by PoloBello** [comment]
Yes, it's working this way but I'll wait an update to install it again, I like being able to save mid game.

**Comment by Caseyckk** [comment]
When loading a saved settlement with this mod the save errors.
If you start and finish one all in one go though it is fine. 
If you need to continue a saved town, you will need to remove the mod before it will load.
